apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-cleanup-operator
  namespace: pod-cleanup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-cleanup-operator
  namespace: pod-cleanup
rules:
  - apiGroups:
      - "*"
    resources:
      - jobs
      - pods
      - pods/log
    verbs:
      - get
      - list
      - delete
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-cleanup-operator
  namespace: pod-cleanup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-cleanup-operator
subjects:
  - kind: ServiceAccount
    name: pod-cleanup-operator
    namespace: pod-cleanup
